<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class KotaSeeder extends Seeder
{
	public function run()
	{
		$data = [];
		$myTime = new Time('now');
		$singledata = ['kota_id'=>'1101', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN SIMEULUE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1102', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH SINGKIL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1103', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1104', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH TENGGARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1105', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1106', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1107', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1108', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH BESAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1109', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN PIE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1110', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN BIREUEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1111', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1112', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH BARAT DAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1113', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN GAYO LUES'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1114', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH TAMIANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1115', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN NAGAN RAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1116', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN ACEH JAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1117', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN BENER MERIAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1118', 'provinsi_id'=>'11', 'kota_name'=> 'KABUPATEN PIE JAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1171', 'provinsi_id'=>'11', 'kota_name'=> 'KOTA BANDA ACEH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1172', 'provinsi_id'=>'11', 'kota_name'=> 'KOTA SABANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1173', 'provinsi_id'=>'11', 'kota_name'=> 'KOTA LANGSA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1174', 'provinsi_id'=>'11', 'kota_name'=> 'KOTA LHOKSEUMAWE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1175', 'provinsi_id'=>'11', 'kota_name'=> 'KOTA SUBULUSSALAM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1201', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN NIAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1202', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN MANDAILING NATAL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1203', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN TAPANULI SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1204', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN TAPANULI TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1205', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN TAPANULI UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1206', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN TOBA SAMOSIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1207', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN LABUHAN BATU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1208', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN ASAHAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1209', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN SIMALUNGUN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1210', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN DAIRI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1211', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN KARO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1212', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN DELI SERDANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1213', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN LANGKAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1214', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN NIAS SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1215', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN HUMBANG HASUNDUTAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1216', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN PAKPAK BHARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1217', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN SAMOSIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1218', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN SERDANG BEDAGAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1219', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN BATU BARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1220', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN PADANG LAWAS UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1221', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN PADANG LAWAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1222', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN LABUHAN BATU SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1223', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN LABUHAN BATU UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1224', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN NIAS UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1225', 'provinsi_id'=>'12', 'kota_name'=> 'KABUPATEN NIAS BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1271', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA SIBOLGA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1272', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA TANJUNG BALAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1273', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA PEMATANG SIANTAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1274', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA TEBING TINGGI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1275', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA MEDAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1276', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA BINJAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1277', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA PADANGSIMPUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1278', 'provinsi_id'=>'12', 'kota_name'=> 'KOTA GUNUNGSITOLI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1301', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN KEPULAUAN MENTAWAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1302', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN PESISIR SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1303', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN SOLOK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1304', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN SIJUNJUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1305', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN TANAH DATAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1306', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN PADANG PARIAMAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1307', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN AGAM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1308', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN LIMA PULUH KOTA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1309', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN PASAMAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1310', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN SOLOK SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1311', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN DHARMASRAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1312', 'provinsi_id'=>'13', 'kota_name'=> 'KABUPATEN PASAMAN BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1371', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA PADANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1372', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA SOLOK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1373', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA SAWAH LUNTO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1374', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA PADANG PANJANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1375', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA BUKITTINGGI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1376', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA PAYAKUMBUH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1377', 'provinsi_id'=>'13', 'kota_name'=> 'KOTA PARIAMAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1401', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN KUANTAN SINGINGI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1402', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN INDRAGIRI HULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1403', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN INDRAGIRI HILIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1404', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN PELALAWAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1405', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN S I A K'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1406', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN KAMPAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1407', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN ROKAN HULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1408', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN BENGKALIS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1409', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN ROKAN HILIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1410', 'provinsi_id'=>'14', 'kota_name'=> 'KABUPATEN KEPULAUAN MERANTI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1471', 'provinsi_id'=>'14', 'kota_name'=> 'KOTA PEKANBARU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1473', 'provinsi_id'=>'14', 'kota_name'=> 'KOTA D U M A I'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1501', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN KERINCI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1502', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN MERANGIN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1503', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN SAROLANGUN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1504', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN BATANG HARI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1505', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN MUARO JAMBI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1506', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN TANJUNG JABUNG TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1507', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN TANJUNG JABUNG BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1508', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN TEBO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1509', 'provinsi_id'=>'15', 'kota_name'=> 'KABUPATEN BUNGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1571', 'provinsi_id'=>'15', 'kota_name'=> 'KOTA JAMBI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1572', 'provinsi_id'=>'15', 'kota_name'=> 'KOTA SUNGAI PENUH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1601', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN OGAN KOMERING ULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1602', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN OGAN KOMERING ILIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1603', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN MUARA ENIM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1604', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN LAHAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1605', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN MUSI RAWAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1606', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN MUSI BANYUASIN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1607', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN BANYU ASIN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1608', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN OGAN KOMERING ULU SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1609', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN OGAN KOMERING ULU TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1610', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN OGAN ILIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1611', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN EMPAT LAWANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1612', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1613', 'provinsi_id'=>'16', 'kota_name'=> 'KABUPATEN MUSI RAWAS UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1671', 'provinsi_id'=>'16', 'kota_name'=> 'KOTA PALEMBANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1672', 'provinsi_id'=>'16', 'kota_name'=> 'KOTA PRABUMULIH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1673', 'provinsi_id'=>'16', 'kota_name'=> 'KOTA PAGAR ALAM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1674', 'provinsi_id'=>'16', 'kota_name'=> 'KOTA LUBUKLINGGAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1701', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN BENGKULU SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1702', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN REJANG LEBONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1703', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN BENGKULU UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1704', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN KAUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1705', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN SELUMA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1706', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN MUKOMUKO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1707', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN LEBONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1708', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN KEPAHIANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1709', 'provinsi_id'=>'17', 'kota_name'=> 'KABUPATEN BENGKULU TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1771', 'provinsi_id'=>'17', 'kota_name'=> 'KOTA BENGKULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1801', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN LAMPUNG BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1802', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN TANGGAMUS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1803', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN LAMPUNG SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1804', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN LAMPUNG TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1805', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN LAMPUNG TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1806', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN LAMPUNG UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1807', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN WAY KANAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1808', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN TULANGBAWANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1809', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN PESAWARAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1810', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN PRINGSEWU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1811', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN MESUJI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1812', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN TULANG BAWANG BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1813', 'provinsi_id'=>'18', 'kota_name'=> 'KABUPATEN PESISIR BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1871', 'provinsi_id'=>'18', 'kota_name'=> 'KOTA BANDAR LAMPUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1872', 'provinsi_id'=>'18', 'kota_name'=> 'KOTA METRO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1901', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BANGKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1902', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BELITUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1903', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BANGKA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1904', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BANGKA TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1905', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BANGKA SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1906', 'provinsi_id'=>'19', 'kota_name'=> 'KABUPATEN BELITUNG TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'1971', 'provinsi_id'=>'19', 'kota_name'=> 'KOTA PANGKAL PINANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2101', 'provinsi_id'=>'21', 'kota_name'=> 'KABUPATEN KARIMUN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2102', 'provinsi_id'=>'21', 'kota_name'=> 'KABUPATEN BINTAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2103', 'provinsi_id'=>'21', 'kota_name'=> 'KABUPATEN NATUNA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2104', 'provinsi_id'=>'21', 'kota_name'=> 'KABUPATEN LINGGA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2105', 'provinsi_id'=>'21', 'kota_name'=> 'KABUPATEN KEPULAUAN ANAMBAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2171', 'provinsi_id'=>'21', 'kota_name'=> 'KOTA B A T A M'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'2172', 'provinsi_id'=>'21', 'kota_name'=> 'KOTA TANJUNG PINANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3101', 'provinsi_id'=>'31', 'kota_name'=> 'KABUPATEN KEPULAUAN SERIBU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3171', 'provinsi_id'=>'31', 'kota_name'=> 'KOTA JAKARTA SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3172', 'provinsi_id'=>'31', 'kota_name'=> 'KOTA JAKARTA TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3173', 'provinsi_id'=>'31', 'kota_name'=> 'KOTA JAKARTA PUSAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3174', 'provinsi_id'=>'31', 'kota_name'=> 'KOTA JAKARTA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3175', 'provinsi_id'=>'31', 'kota_name'=> 'KOTA JAKARTA UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3201', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN BOGOR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3202', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN SUKABUMI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3203', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN CIANJUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3204', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN BANDUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3205', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN GARUT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3206', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN TASIKMALAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3207', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN CIAMIS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3208', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN KUNINGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3209', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN CIREBON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3210', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN MAJALENGKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3211', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN SUMEDANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3212', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN INDRAMAYU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3213', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN SUBANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3214', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN PURWAKARTA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3215', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN KARAWANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3216', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN BEKASI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3217', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN BANDUNG BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3218', 'provinsi_id'=>'32', 'kota_name'=> 'KABUPATEN PANGANDARAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3271', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA BOGOR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3272', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA SUKABUMI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3273', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA BANDUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3274', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA CIREBON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3275', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA BEKASI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3276', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA DEPOK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3277', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA CIMAHI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3278', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA TASIKMALAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3279', 'provinsi_id'=>'32', 'kota_name'=> 'KOTA BANJAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3301', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN CILACAP'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3302', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BANYUMAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3303', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN PURBALINGGA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3304', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BANJARNEGARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3305', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN KEBUMEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3306', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN PURWOREJO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3307', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN WONOSOBO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3308', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN MAGELANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3309', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BOYOLALI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3310', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN KLATEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3311', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN SUKOHARJO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3312', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN WONOGIRI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3313', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN KARANGANYAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3314', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN SRAGEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3315', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN GROBOGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3316', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BLORA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3317', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN REMBANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3318', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN PATI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3319', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN KUDUS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3320', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN JEPARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3321', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN DEMAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3322', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN SEMARANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3323', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN TEMANGGUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3324', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN KENDAL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3325', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BATANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3326', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN PEKALONGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3327', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN PEMALANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3328', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN TEGAL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3329', 'provinsi_id'=>'33', 'kota_name'=> 'KABUPATEN BREBES'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3371', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA MAGELANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3372', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA SURAKARTA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3373', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA SALATIGA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3374', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA SEMARANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3375', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA PEKALONGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3376', 'provinsi_id'=>'33', 'kota_name'=> 'KOTA TEGAL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3401', 'provinsi_id'=>'34', 'kota_name'=> 'KABUPATEN KULON PROGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3402', 'provinsi_id'=>'34', 'kota_name'=> 'KABUPATEN BANTUL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3403', 'provinsi_id'=>'34', 'kota_name'=> 'KABUPATEN GUNUNG KUL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3404', 'provinsi_id'=>'34', 'kota_name'=> 'KABUPATEN SLEMAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3471', 'provinsi_id'=>'34', 'kota_name'=> 'KOTA YOGYAKARTA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3501', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN PACITAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3502', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN PONOROGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3503', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN TRENGGALEK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3504', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN TULUNGAGUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3505', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN BLITAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3506', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN KEDIRI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3507', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN MALANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3508', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN LUMAJANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3509', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN JEMBER'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3510', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN BANYUWANGI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3511', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN BONDOWOSO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3512', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN SITUBONDO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3513', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN PROBOLINGGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3514', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN PASURUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3515', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN SOARJO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3516', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN MOJOKERTO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3517', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN JOMBANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3518', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN NGANJUK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3519', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN MADIUN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3520', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN MAGETAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3521', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN NGAWI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3522', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN BOJONEGORO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3523', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN TUBAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3524', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN LAMONGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3525', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN GRESIK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3526', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN BANGKALAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3527', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN SAMPANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3528', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN PAMEKASAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3529', 'provinsi_id'=>'35', 'kota_name'=> 'KABUPATEN SUMENEP'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3571', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA KEDIRI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3572', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA BLITAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3573', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA MALANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3574', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA PROBOLINGGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3575', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA PASURUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3576', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA MOJOKERTO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3577', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA MADIUN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3578', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA SURABAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3579', 'provinsi_id'=>'35', 'kota_name'=> 'KOTA BATU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3601', 'provinsi_id'=>'36', 'kota_name'=> 'KABUPATEN PANDEGLANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3602', 'provinsi_id'=>'36', 'kota_name'=> 'KABUPATEN LEBAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3603', 'provinsi_id'=>'36', 'kota_name'=> 'KABUPATEN TANGERANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3604', 'provinsi_id'=>'36', 'kota_name'=> 'KABUPATEN SERANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3671', 'provinsi_id'=>'36', 'kota_name'=> 'KOTA TANGERANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3672', 'provinsi_id'=>'36', 'kota_name'=> 'KOTA CILEGON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3673', 'provinsi_id'=>'36', 'kota_name'=> 'KOTA SERANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'3674', 'provinsi_id'=>'36', 'kota_name'=> 'KOTA TANGERANG SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5101', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN JEMBRANA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5102', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN TABANAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5103', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN BADUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5104', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN GIANYAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5105', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN KLUNGKUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5106', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN BANGLI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5107', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN KARANG ASEM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5108', 'provinsi_id'=>'51', 'kota_name'=> 'KABUPATEN BULELENG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5171', 'provinsi_id'=>'51', 'kota_name'=> 'KOTA DENPASAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5201', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN LOMBOK BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5202', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN LOMBOK TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5203', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN LOMBOK TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5204', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN SUMBAWA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5205', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN DOMPU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5206', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN BIMA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5207', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN SUMBAWA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5208', 'provinsi_id'=>'52', 'kota_name'=> 'KABUPATEN LOMBOK UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5271', 'provinsi_id'=>'52', 'kota_name'=> 'KOTA MATARAM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5272', 'provinsi_id'=>'52', 'kota_name'=> 'KOTA BIMA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5301', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SUMBA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5302', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SUMBA TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5303', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN KUPANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5304', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN TIMOR TENGAH SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5305', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN TIMOR TENGAH UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5306', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN BELU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5307', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN ALOR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5308', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN LEMBATA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5309', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN FLORES TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5310', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SIKKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5311', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN ENDE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5312', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN NGADA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5313', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN MANGGARAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5314', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN ROTE NDAO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5315', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN MANGGARAI BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5316', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SUMBA TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5317', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SUMBA BARAT DAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5318', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN NAGEKEO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5319', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN MANGGARAI TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5320', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN SABU RAIJUA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5321', 'provinsi_id'=>'53', 'kota_name'=> 'KABUPATEN MALAKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'5371', 'provinsi_id'=>'53', 'kota_name'=> 'KOTA KUPANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6101', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN SAMBAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6102', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN BENGKAYANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6103', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN LANDAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6104', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN MEMPAWAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6105', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN SANGGAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6106', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN KETAPANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6107', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN SINTANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6108', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN KAPUAS HULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6109', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN SEKADAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6110', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN MELAWI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6111', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN KAYONG UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6112', 'provinsi_id'=>'61', 'kota_name'=> 'KABUPATEN KUBU RAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6171', 'provinsi_id'=>'61', 'kota_name'=> 'KOTA PONTIANAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6172', 'provinsi_id'=>'61', 'kota_name'=> 'KOTA SINGKAWANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6201', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN KOTAWARINGIN BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6202', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN KOTAWARINGIN TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6203', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN KAPUAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6204', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN BARITO SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6205', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN BARITO UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6206', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN SUKAMARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6207', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN LAMANDAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6208', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN SERUYAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6209', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN KATINGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6210', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN PULANG PISAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6211', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN GUNUNG MAS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6212', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN BARITO TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6213', 'provinsi_id'=>'62', 'kota_name'=> 'KABUPATEN MURUNG RAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6271', 'provinsi_id'=>'62', 'kota_name'=> 'KOTA PALANGKA RAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6301', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN TANAH LAUT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6302', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN KOTA BARU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6303', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN BANJAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6304', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN BARITO KUALA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6305', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN TAPIN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6306', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN HULU SUNGAI SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6307', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN HULU SUNGAI TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6308', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN HULU SUNGAI UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6309', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN TABALONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6310', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN TANAH BUMBU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6311', 'provinsi_id'=>'63', 'kota_name'=> 'KABUPATEN BALANGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6371', 'provinsi_id'=>'63', 'kota_name'=> 'KOTA BANJARMASIN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6372', 'provinsi_id'=>'63', 'kota_name'=> 'KOTA BANJAR BARU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6401', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN PASER'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6402', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN KUTAI BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6403', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN KUTAI KARTANEGARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6404', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN KUTAI TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6405', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN BERAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6409', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN PENAJAM PASER UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6411', 'provinsi_id'=>'64', 'kota_name'=> 'KABUPATEN MAHAKAM HULU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6471', 'provinsi_id'=>'64', 'kota_name'=> 'KOTA BALIKPAPAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6472', 'provinsi_id'=>'64', 'kota_name'=> 'KOTA SAMARINDA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6474', 'provinsi_id'=>'64', 'kota_name'=> 'KOTA BONTANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6501', 'provinsi_id'=>'65', 'kota_name'=> 'KABUPATEN MALINAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6502', 'provinsi_id'=>'65', 'kota_name'=> 'KABUPATEN BULUNGAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6503', 'provinsi_id'=>'65', 'kota_name'=> 'KABUPATEN TANA TUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6504', 'provinsi_id'=>'65', 'kota_name'=> 'KABUPATEN NUNUKAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'6571', 'provinsi_id'=>'65', 'kota_name'=> 'KOTA TARAKAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7101', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN BOLAANG MONGONDOW'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7102', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN MINAHASA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7103', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN KEPULAUAN SANGIHE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7104', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN KEPULAUAN TALAUD'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7105', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN MINAHASA SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7106', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN MINAHASA UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7107', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN BOLAANG MONGONDOW UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7108', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN SIAU TAGULANDANG BIARO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7109', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN MINAHASA TENGGARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7110', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN BOLAANG MONGONDOW SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7111', 'provinsi_id'=>'71', 'kota_name'=> 'KABUPATEN BOLAANG MONGONDOW TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7171', 'provinsi_id'=>'71', 'kota_name'=> 'KOTA MANADO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7172', 'provinsi_id'=>'71', 'kota_name'=> 'KOTA BITUNG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7173', 'provinsi_id'=>'71', 'kota_name'=> 'KOTA TOMOHON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7174', 'provinsi_id'=>'71', 'kota_name'=> 'KOTA KOTAMOBAGU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7201', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN BANGGAI KEPULAUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7202', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN BANGGAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7203', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN MOROWALI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7204', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN POSO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7205', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN DONGGALA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7206', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN TOLI-TOLI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7207', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN BUOL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7208', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN PARIGI MOUTONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7209', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN TOJO UNA-UNA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7210', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN SIGI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7211', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN BANGGAI LAUT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7212', 'provinsi_id'=>'72', 'kota_name'=> 'KABUPATEN MOROWALI UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7271', 'provinsi_id'=>'72', 'kota_name'=> 'KOTA PALU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7301', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN KEPULAUAN SELAYAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7302', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN BULUKUMBA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7303', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN BANTAENG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7304', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN JENEPONTO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7305', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN TAKALAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7306', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN GOWA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7307', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN SINJAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7308', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN MAROS'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7309', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN PANGKAJENE DAN KEPULAUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7310', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN BARRU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7311', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN BONE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7312', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN SOPPENG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7313', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN WAJO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7314', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN SENRENG RAPPANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7315', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN PINRANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7316', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN ENREKANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7317', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN LUWU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7318', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN TANA TORAJA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7322', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN LUWU UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7325', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN LUWU TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7326', 'provinsi_id'=>'73', 'kota_name'=> 'KABUPATEN TORAJA UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7371', 'provinsi_id'=>'73', 'kota_name'=> 'KOTA MAKASSAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7372', 'provinsi_id'=>'73', 'kota_name'=> 'KOTA PAREPARE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7373', 'provinsi_id'=>'73', 'kota_name'=> 'KOTA PALOPO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7401', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN BUTON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7402', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN MUNA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7403', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KONAWE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7404', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KOLAKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7405', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KONAWE SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7406', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN BOMBANA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7407', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN WAKATOBI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7408', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KOLAKA UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7409', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN BUTON UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7410', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KONAWE UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7411', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KOLAKA TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7412', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN KONAWE KEPULAUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7413', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN MUNA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7414', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN BUTON TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7415', 'provinsi_id'=>'74', 'kota_name'=> 'KABUPATEN BUTON SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7471', 'provinsi_id'=>'74', 'kota_name'=> 'KOTA KENDARI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7472', 'provinsi_id'=>'74', 'kota_name'=> 'KOTA BAUBAU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7501', 'provinsi_id'=>'75', 'kota_name'=> 'KABUPATEN BOALEMO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7502', 'provinsi_id'=>'75', 'kota_name'=> 'KABUPATEN GORONTALO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7503', 'provinsi_id'=>'75', 'kota_name'=> 'KABUPATEN POHUWATO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7504', 'provinsi_id'=>'75', 'kota_name'=> 'KABUPATEN BONE BOLANGO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7505', 'provinsi_id'=>'75', 'kota_name'=> 'KABUPATEN GORONTALO UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7571', 'provinsi_id'=>'75', 'kota_name'=> 'KOTA GORONTALO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7601', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN MAJENE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7602', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN POLEWALI MANDAR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7603', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN MAMASA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7604', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN MAMUJU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7605', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN MAMUJU UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'7606', 'provinsi_id'=>'76', 'kota_name'=> 'KABUPATEN MAMUJU TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8101', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN MALUKU TENGGARA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8102', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN MALUKU TENGGARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8103', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN MALUKU TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8104', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN BURU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8105', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN KEPULAUAN ARU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8106', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN SERAM BAGIAN BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8107', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN SERAM BAGIAN TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8108', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN MALUKU BARAT DAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8109', 'provinsi_id'=>'81', 'kota_name'=> 'KABUPATEN BURU SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8171', 'provinsi_id'=>'81', 'kota_name'=> 'KOTA AMBON'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8172', 'provinsi_id'=>'81', 'kota_name'=> 'KOTA TUAL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8201', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN HALMAHERA BARAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8202', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN HALMAHERA TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8203', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN KEPULAUAN SULA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8204', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN HALMAHERA SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8205', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN HALMAHERA UTARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8206', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN HALMAHERA TIMUR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8207', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN PULAU MOROTAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8208', 'provinsi_id'=>'82', 'kota_name'=> 'KABUPATEN PULAU TALIABU'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8271', 'provinsi_id'=>'82', 'kota_name'=> 'KOTA TERNATE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'8272', 'provinsi_id'=>'82', 'kota_name'=> 'KOTA TORE KEPULAUAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9101', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN FAKFAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9102', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN KAIMANA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9103', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN TELUK WONDAMA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9104', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN TELUK BINTUNI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9105', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN MANOKWARI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9106', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN SORONG SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9107', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN SORONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9108', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN RAJA AMPAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9109', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN TAMBRAUW'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9110', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN MAYBRAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9111', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN MANOKWARI SELATAN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9112', 'provinsi_id'=>'91', 'kota_name'=> 'KABUPATEN PEGUNUNGAN ARFAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9171', 'provinsi_id'=>'91', 'kota_name'=> 'KOTA SORONG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9401', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN MERAUKE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9402', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN JAYAWIJAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9403', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN JAYAPURA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9404', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN NABIRE'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9408', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN KEPULAUAN YAPEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9409', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN BIAK NUMFOR'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9410', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN PANIAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9411', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN PUNCAK JAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9412', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN MIMIKA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9413', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN BOVEN DIGOEL'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9414', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN MAPPI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9415', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN ASMAT'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9416', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN YAHUKIMO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9417', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN PEGUNUNGAN BINTANG'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9418', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN TOLIKARA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9419', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN SARMI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9420', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN KEEROM'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9426', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN WAROPEN'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9427', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN SUPIORI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9428', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN MAMBERAMO RAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9429', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN NDUGA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9430', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN LANNY JAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9431', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN MAMBERAMO TENGAH'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9432', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN YALIMO'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9433', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN PUNCAK'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9434', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN DOGIYAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9435', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN INTAN JAYA'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9436', 'provinsi_id'=>'94', 'kota_name'=> 'KABUPATEN DEIYAI'];
		array_push($data, $singledata);
		$singledata = ['kota_id'=>'9471', 'provinsi_id'=>'94', 'kota_name'=> 'KOTA JAYAPURA'];
		array_push($data, $singledata);

		$this->db->table('kota')->insertBatch($data);
	}
}
